name: BossDamageCalc
version: '1.0-SNAPSHOT'
main: org.qpneruy.bossDamageCalc.BossDamageCalc
api-version: '1.20'
authors: [ qpneruy ]
description: Plugin Tính Damage đánh Boss, Bản Quyền của TST - TaoSinhTon

commands:
  bossDamageCalc:
    description: "yep, BossDamageCalc"
    aliases: [bossDamageCalc, bdac]
    permission: BossDamageCalc.BossDamageCalc
